# Generated by Django 3.1.5 on 2021-03-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210121_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='lat',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='lon',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='accounts.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitalspecialitybed',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_beds', to='accounts.hospital'),
        ),
    ]
