# Generated by Django 3.1.5 on 2021-04-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalspecialitybed',
            name='speciality_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.specialitybed'),
        ),
    ]
